@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0


class EditHabitView {
}

class EditHabitViewModel {
    + listHabit()
    + listHabitCategories()
    - getHabitById()
    + editHabit()
    + validateData()
    - getHabitCategoryById()
}

class Habit {
    - id
    - title
    - description
    - measurement
    - unitOfMeasurement
    - startDate
    - endDate
    - frequency
    - priority
    - categoryId
}

class HabitDAO {
    + listHabits()
    + updateHabit()
    + findHabitById()
}

class HabitCategoryDAO {
    + listHabitCategories()
    + findHabitCategoryById()
}

class HabitCategoryRepository {
    + listHabitCategories()
    + findHabitCategoryById()
}

class HabitRepository {
    + listHabits()
    + findHabitById()
    + updateHabit()
}

class Database {
    + habitCategoryDAO()
    + habitDAO()
}


EditHabitView -> EditHabitView : instance
EditHabitViewModel -> EditHabitViewModel : instance
HabitRepository -> HabitRepository : instance
Database -> Database : instance


EditHabitView --> EditHabitViewModel : creates
EditHabitViewModel --> HabitRepository : habitRepository
EditHabitViewModel --> HabitCategoryRepository : habitCategoryRepository

HabitRepository --> Habit : creates
HabitRepository --> HabitDAO
HabitCategoryRepository --> HabitCategoryDAO

Database --> HabitDAO
Database --> HabitCategoryDAO



@enduml
