@startuml
left to right direction
actor User

User --> (US001)
User --> (US002)
User --> (US003)
User --> (US004)
User --> (US005)
User --> (US006)
User --> (US007)

(US001) --> (Create a Habit) : Description
(US002) --> (Delete a Habit) : Description
(US003) --> (Edit a Habit) : Description
(US004) --> (Pause a Habit) : Description
(US005) --> (Complete a Habit) : Description
(US006) --> (Create a Database) : Description
(US007) --> (View Habit Progress) : Description
@enduml
