@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype ortho
left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model


class Habit {
    title
    description
    measurement
    priority
    unit of measurement
    frequency
    start date
    end date
}

class Category {
    image
    description
}


Habit"*" ----> "1"Category: belongs to

@enduml