@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "User" as User
participant ":System" as System

activate User

    User -> System : asks to edit a habit
    activate System

        System --> User : shows habit category list and asks to select one
    deactivate System

        User -> System : selects a habit category
    activate System

        System --> User : requests data (title, description, measurement, priority, unit of measurement, start date, end date, frequency)
    deactivate System

    User -> System : types requested data
    activate System

        System --> User : displays operation success
    deactivate System

@enduml